export type { Answer, MultipleSelectAnswer, SingleSelectAnswer, TextAnswer } from './answer'
export type { Data, SelectData, TextData } from './data'
export type { Inalia } from './inalia'
export type { ChartType, MultipleSelectQuestion, Question, QuestionType, SingleSelectQuestion, TextQuestion } from './question'
export type { Talk } from './talk'
